# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

MAINTAINER BlankGodd "blankgodd33@gmail.com"

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

ENTRYPOINT [ "python" ]

CMD [ "ecom/ecom.py" ]

